//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Health.Med.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Health.Med.Exceptions.ErrorsMessages", typeof(ErrorsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpo do e-mail em branco.
        /// </summary>
        public static string BlankBody {
            get {
                return ResourceManager.GetString("BlankBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF em branco.
        /// </summary>
        public static string BlankCPF {
            get {
                return ResourceManager.GetString("BlankCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR em branco.
        /// </summary>
        public static string BlankCR {
            get {
                return ResourceManager.GetString("BlankCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email em branco.
        /// </summary>
        public static string BlankEmail {
            get {
                return ResourceManager.GetString("BlankEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome em branco.
        /// </summary>
        public static string BlankName {
            get {
                return ResourceManager.GetString("BlankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha em branco.
        /// </summary>
        public static string BlankPassword {
            get {
                return ResourceManager.GetString("BlankPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatário em branco.
        /// </summary>
        public static string BlankRecipient {
            get {
                return ResourceManager.GetString("BlankRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assunto em branco.
        /// </summary>
        public static string BlankSubject {
            get {
                return ResourceManager.GetString("BlankSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente já tem uma consulta agendada para o dia {0}.
        /// </summary>
        public static string ClientAlreadyConsultationSchedule {
            get {
                return ResourceManager.GetString("ClientAlreadyConsultationSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente sem permissão.
        /// </summary>
        public static string ClientWithoutPermission {
            get {
                return ResourceManager.GetString("ClientWithoutPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF já cadastrado.
        /// </summary>
        public static string CPFAlreadyRegistered {
            get {
                return ResourceManager.GetString("CPFAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro no órgão regional já cadastrado.
        /// </summary>
        public static string CRAlreadyRegistered {
            get {
                return ResourceManager.GetString("CRAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doutor já tem uma consulta agendada para o dia {0}.
        /// </summary>
        public static string DoctorAlreadyConsultationSchedule {
            get {
                return ResourceManager.GetString("DoctorAlreadyConsultationSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Médico sem permissão.
        /// </summary>
        public static string DoctorWithoutPermission {
            get {
                return ResourceManager.GetString("DoctorWithoutPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email já cadastrado.
        /// </summary>
        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token expirado.
        /// </summary>
        public static string ExpiredToken {
            get {
                return ResourceManager.GetString("ExpiredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atual inválida.
        /// </summary>
        public static string InvalidCurrentPassword {
            get {
                return ResourceManager.GetString("InvalidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou senha incorretos.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail destinatário em branco.
        /// </summary>
        public static string InvalidRecipientEmail {
            get {
                return ResourceManager.GetString("InvalidRecipientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha deve ter ao menos seis caracteres.
        /// </summary>
        public static string MinimumSixCharacters {
            get {
                return ResourceManager.GetString("MinimumSixCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token não encontrado.
        /// </summary>
        public static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário sem permissão.
        /// </summary>
        public static string UserWithoutPermission {
            get {
                return ResourceManager.GetString("UserWithoutPermission", resourceCulture);
            }
        }
    }
}
