name: Central Pipeline

on:
  push:
    branches:
      - main

jobs:
  identify_and_trigger:
    runs-on: Linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Obter mensagem de commit
        id: commit_message
        run: |
          MESSAGE=$(git log -1 --pretty=%B | tr -d '\n' | sed 's/:/-/g')
          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV

      - name: Identificar e disparar a pipeline do projeto
        run: |
          if echo "$MESSAGE" | grep -q "ocelot"; then
            echo "Executando workflow Ocelot"
            gh workflow run ocelot.yaml
          elif echo "$MESSAGE" | grep -q "notification"; then
            echo "Executando workflow Notification"
            gh workflow run notification.yaml
          elif echo "$MESSAGE" | grep -q "client"; then
            echo "Executando workflow Client"
            gh workflow run client.yaml
          elif echo "$MESSAGE" | grep -q "doctor"; then
            echo "Executando workflow Doctor"
            gh workflow run doctor.yaml
          elif echo "$MESSAGE" | grep -q "user"; then
            echo "Executando workflow User"
            gh workflow run user.yaml
          elif echo "$MESSAGE" | grep -q "consultation"; then
            echo "Executando workflow Consultation"
            gh workflow run consultation.yaml
          else
            echo "Nenhum workflow correspondente encontrado."
          fi

        env: 
          GH_TOKEN: ${{ secrets.CONFIG_REPO_TOKEN }}
