name: CI/CD for Doctor

on:
  workflow_dispatch:

jobs:  
  build-and-push:
    name: Build, Test, and Publish Docker Image - Doctor
    runs-on: Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace appsettings for Doctor
        run: |
          echo "Replacing appsettings for Doctor"
          cmd /C "copy /Y c:\appsettings\doctor\appsettings.json %GITHUB_WORKSPACE%\Health.Med.Doctor\Doctor.Api\appsettings.json"
          cmd /C "copy /Y c:\appsettings\doctor\appsettings.IntegrationTests.json %GITHUB_WORKSPACE%\Health.Med.Doctor\Doctor.Api\appsettings.IntegrationTests.json"

      - name: Restore dependencies
        run: |
          echo "Restoring dependencies for Doctor"
          cd Health.Med.Doctor/
          dotnet restore

      - name: Build the Doctor
        run: |
          echo "Building the Doctor"
          dotnet build Health.Med.Doctor/Health.Med.Doctor.sln --no-restore --configuration Release

      - name: Run unit tests
        run: |
          echo "Running unit tests"
          dotnet test Health.Med.Doctor/Doctor.Tests/Doctor.Tests.csproj --no-build --configuration Release --logger "trx;LogFileName=unit-test-doctor-results.trx"

      - name: Run integration tests
        run: |
          echo "Running integration tests"
          dotnet test Health.Med.Doctor/Doctor.Integration.Tests/Doctor.Integration.Tests.csproj --no-build --configuration Release --logger "trx;LogFileName=unit-integration-test-doctor-results.trx"
      
      - name: Login to Docker Hub
        run: |
          echo "Logging into Docker Hub"
          $env:DOCKERHUB_PASSWORD="${{ secrets.DOCKERHUB_PASSWORD }}"
          $env:DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Username: $env:DOCKERHUB_USERNAME"
          echo "Password: $env:DOCKERHUB_PASSWORD"
          docker login -u $env:DOCKERHUB_USERNAME -p $env:DOCKERHUB_PASSWORD

      - name: Build and Push Docker Image for Doctor
        run: |
          echo "Building and pushing Docker image for Doctor"
          $IMAGE_NAME="natanroberto182/doctor:latest"
          docker build -f Health.Med.Doctor/Dockerfile -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  notify-config-repo:
    name: Notify Configurations Repository
    runs-on: Windows
    needs: build-and-push

    steps:
      - name: Set the list of services to notify
        id: services
        run: |
          echo "Determining which services were built successfully"
          $services="doctor"
          echo "Services to notify: $services"
          echo "services=$services" >> $GITHUB_OUTPUT

      - name: Notify Configuration Repository
        run: |
          curl.exe -X POST ^
            -H "Accept: application/vnd.github.everest-preview+json" ^
            -H "Authorization: token ${{ secrets.CONFIG_REPO_TOKEN }}" ^
            -d "{\"event_type\": \"update-configurations\", \"client_payload\": {\"services\": \"doctor\"}}" ^
            https://api.github.com/repos/natanrobertoxavier/Hackathon.Config.Repo/dispatches
        shell: cmd